### PR TITLE
VSCode Task Provider Documentation

### PR DESCRIPTION
**Pull request by knowsuchagency**
## Pull Request Check List

- [x] A news fragment is added in `news/` describing what is new.
- [x] Test cases added for changed code.

## Describe what you have changed in this PR.

I added a link to a [VSCode Task Provider extension](https://marketplace.visualstudio.com/items?itemName=knowsuchagency.pdm-task-provider) to the documentation for VSCode integration. 

My apologies, but I couldn't figure out how to properly add an entry in `/news` for `towncrier`, but would be happy to do so if given instructions on how.

Thanks!

### CODE REVIEW

**Comment by frostming** [comment]
Put your release note into a file named `280.doc.md`

**Comment by knowsuchagency** [comment]
Done. Should I also commit the update to the changelog from `towncrier`?

**Comment by frostming** [comment]
You don't need to do that. It's auto-generated.

**Comment by frostming** [comment]
Nice extension, thanks for contribution.

**Comment by knowsuchagency** [comment]
Thanks for making such an awesome tool 🤙 

Excited to see it become more broadly adopted within the community

**Pull request merged**
