### PR TITLE
Add ability to read venv location from file

### PR DESCRIPTION
**Pull request by uranusjr**
## Pull Request Check List

- [x] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

### CODE REVIEW

**Comment by frostming** [comment]
Since the Python interpreter path is already written in the `.pdm.toml` under the project, I would prefer Single Source of Truth.

I am working on #219 so that one can achieve this by following:

```bash
$ pdm use -f <python_path>
```

Tell me if it is OK or you still insist on the current implementation.

**Comment by uranusjr** [comment]
I would prefer if it’s possible to also do `pdm use <path-to-virtual-environment>`. Easier to tab-complete, especially when I switch between Windows and POSIX 🙂

**Comment by frostming** [comment]
I got that and created #221 to track it.

**Comment by frostming** [comment]
#221 and #219 are already implemented in the main branch, I would like to close this PR

**Pull request closed without merging**
